encoding: utf-8
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
gems:
  - jekyll-redirect-from
prose:
  media: "files"
  siteurl: "http://farmingtonrobotics.org"
